### ISSUE TITLE
Anlegen einer Rufnummerliste im Adminbereich

### ISSUE THREAD

**Issue by Jnig** [okinoby/Server#28]
Auszug Requirements:
Es muss ein Webinterface geben um die Rufnummern zu bearbeiten.
Beim ändern/anlegen und löschen von Objekten muss mitgeloggt werden, welcher User die Änderungen durchgeführt hat und bei Änderungen der alte und neue Wert des Feldes angezeigt werden.

Hierfür soll folgende Datenbankstruktur (Skizze) genutzt werden:
Name der Institution
Rufnummer der Institution
Kategorie
Foreign-Key auf den Eintrag in der “Hilfe in der Umgebung” Tabelle

**Comment by chris-ho** [comment]
hey zusammen habe grad ein kleines Problem was join statements angeht...

folgendes statement:
select * from geotracking_organization join okinoby_phonelistchangelog on(geotracking_organization.id = okinoby_phonelistchangelog.Org_id) join auth_user on(auth_user.id = okinoby_phonelistchangelog.User_id);

müsste ich haben.

wenn ich Organization.objects.all().select_related('Phonelistchangelog', 'Phonelistchangelog__User') 
verwende bekomme ich Fehlermeldungen, dass Apalten aus der Table Phonelistchangelog fehlen.

derzeit nutze ich den Organzation.objects.raw(statement von oben) als Notlösung.
