### ISSUE TITLE
Medikamenten sollen Standardgrößen hinzugefügt werden können

### ISSUE THREAD

**Issue by blubablub** [okinoby/Server#58]
Medikamenten sollen ein Feld haben, in dem man ein oder mehrere Standardgrößen der Medikamente hinzufügen kann um diese dann in der App bei der Berechnung zu berücksichtigen.

**Comment by blubablub** [comment]
Ich denke mal, du wolltest #59 schließen ;)

**Comment by chris-ho** [comment]
ja wollte es auch eben ändern ;)
